#!/bin/bash

log() {
    echo "[INFO] $1"
}

error() {
    echo "[ERROR] $1" >&2
    exit 1
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        error "Please run as root (use sudo)."
    fi
}

remove_commands() {
    log "Removing installed commands..."

    commands=('netdos' 'netpulse' 'sennet' 'sennet_update' 'sennet_version' 'sennet_uninstall')

    for cmd in "${commands[@]}"; do
        rm -f "/usr/local/bin/$cmd"
        log "$cmd removed."
    done
}

check_root

if [ -f "/etc/os-release" ]; then
    source /etc/os-release
    DISTRIBUTION=$(echo "$ID" | tr '[:upper:]' '[:lower:]')
elif [ -f "/etc/redhat-release" ]; then
    DISTRIBUTION="redhat"
else
    DISTRIBUTION=$(uname -s | tr '[:upper:]' '[:lower:]')
fi

remove_commands

log "Uninstallation complete! Thank you for using Sennet!"