#!/bin/bash

SCRIPT_PATH=$(realpath "$0")
REPO_URL="https://github.com/Preeby/Sennet"
RELEASE_TAG=$(curl -sI "${REPO_URL}/releases/latest" | grep -i 'location' | awk -F '/' '{print $NF}' | tr -d '\r\n')

if [ -z "$RELEASE_TAG" ]; then
    echo "Error: Unable to access GitHub page. Check your internet connection."
    exit 1
fi

CURRENT_VERSION="v1.3"

LATEST_VERSION=$(curl -sI "${REPO_URL}/releases/latest" | grep -i 'location' | awk -F '/' '{print $NF}' | tr -d '\r\n')

if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then 
    if [ "$EUID" -ne 0 ]; then
        echo "Please run with sudo privileges, Sennet is not up to date!"
        exit 1
    fi

    TEMP_DIR=$(mktemp -d)

    git clone --depth=1 --branch "${RELEASE_TAG}" "${REPO_URL}.git" "${TEMP_DIR}"

    cd "${TEMP_DIR}" || exit 1

    chmod +x install.sh

    sudo ./install.sh

    cd -

    rm -r "${TEMP_DIR}"

    sed -i "s/CURRENT_VERSION=\"$CURRENT_VERSION\"/CURRENT_VERSION=\"$LATEST_VERSION\"/" "$SCRIPT_PATH"

    echo "Update complete. Current version: ${RELEASE_TAG}"
else
    echo "You are already using the latest version (${CURRENT_VERSION})."
fi
