#!/bin/bash

UPDATE_SCRIPT="sennet_update"

check_sennet_update() {
    REPO_URL="https://github.com/Preeby/Sennet"
    LATEST_VERSION=$(curl -sI "${REPO_URL}/releases/latest" | grep -i 'location' | awk -F '/' '{print $NF}' | tr -d '\r\n')
    
    CURRENT_VERSION=$(grep -oP 'CURRENT_VERSION="\K[^"]+' sennet_update)

    if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
        echo -e "\e[33mWarning: Sennet is not up to date!\e[0m"
        echo -e "\e[33mLatest version: ${LATEST_VERSION}\e[0m"
        echo -e "\e[33mPlease run sudo sennet_update as soon as possible!\e[0m"
    else
        true
    fi
}

check_sennet_update

if [ -f "$UPDATE_SCRIPT" ]; then
    CURRENT_VERSION=$(grep -oP 'CURRENT_VERSION="\K[^"]+' "$UPDATE_SCRIPT")
    echo "Current version: ${CURRENT_VERSION}"
else
    echo "Error: Sennate_Update not found, please reinstall sennate by downloading it again from github. Thank you!"
fi